# -*- coding: utf-8 -*-
"""Untitled106.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDalQfsFmL18cCOxm8LEZYtyZDCzLwg7
"""

import os
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras import layers, models, backend as K
from sklearn.cluster import KMeans
from sklearn.metrics import jaccard_score

IMG_SIZE = 128
LATENT_DIM = 32
N_CLUSTERS = 2
EPOCHS = 100
BATCH_SIZE = 16
IMG_PATH = '/content/images'
MASK_PATH = '/content/masks'

def load_satellite_data(img_dir, mask_dir):
    x_data, y_true = [], []

    img_list = [f for f in os.listdir(img_dir) if not f.startswith('.')]
    mask_list = [f for f in os.listdir(mask_dir) if not f.startswith('.')]

    img_dict = {f.replace('image', '').split('.')[0]: f for f in img_list}
    mask_dict = {f.replace('mask', '').split('.')[0]: f for f in mask_list}

    common_ids = sorted(set(img_dict.keys()) & set(mask_dict.keys()))
    print(f"--- Dataset Status ---")
    print(f"Matched {len(common_ids)} pairs of images and masks.")

    if len(common_names := common_ids) == 0:
        raise ValueError("Match Failed. Ensure IDs in 'imageXXXX' and 'maskXXXX' are identical.")

    for id_val in common_ids:
        try:
            img_path = os.path.join(img_dir, img_dict[id_val])
            mask_path = os.path.join(mask_dir, mask_dict[id_val])

            img = cv2.imread(img_path)
            if img is None: continue
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

            mzk = cv2.imread(mask_path, 0)
            if mzk is None: continue
            mzk = cv2.resize(mzk, (IMG_SIZE, IMG_SIZE))

            x_data.append(img / 255.0)
            y_true.append((mzk > 127).astype(np.uint8))
        except Exception as e:
            continue

    return np.array(x_data, dtype="float32"), np.array(y_true, dtype="uint8")

X_train, Y_val = load_satellite_data(IMG_PATH, MASK_PATH)

class Sampling(layers.Layer):
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = K.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

encoder_inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = layers.Conv2D(64, 3, activation="relu", strides=2, padding="same")(encoder_inputs)
x = layers.Conv2D(128, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Flatten()(x)
x = layers.Dense(256, activation="relu")(x)
z_mean = layers.Dense(LATENT_DIM, name="z_mean")(x)
z_log_var = layers.Dense(LATENT_DIM, name="z_log_var")(x)
z = Sampling()([z_mean, z_log_var])
encoder = models.Model(encoder_inputs, [z_mean, z_log_var, z], name="encoder")

latent_inputs = layers.Input(shape=(LATENT_DIM,))
x = layers.Dense(32 * 32 * 128, activation="relu")(latent_inputs)
x = layers.Reshape((32, 32, 128))(x)
x = layers.Conv2DTranspose(128, 3, activation="relu", strides=2, padding="same")(x)
x = layers.Conv2DTranspose(64, 3, activation="relu", strides=2, padding="same")(x)
decoder_outputs = layers.Conv2DTranspose(3, 3, activation="sigmoid", padding="same")(x)
decoder = models.Model(latent_inputs, decoder_outputs, name="decoder")

class VAE(models.Model):
    def __init__(self, encoder, decoder, **kwargs):
        super(VAE, self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")

    def train_step(self, data):
        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)

            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(tf.keras.losses.mse(data, reconstruction), axis=(1, 2))
            )

            kl_loss = -0.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
            kl_loss = tf.reduce_mean(tf.reduce_sum(kl_loss, axis=1))
            total_loss = reconstruction_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))

        self.total_loss_tracker.update_state(total_loss)
        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction": reconstruction_loss,
            "kl": kl_loss
        }

vae_model = VAE(encoder, decoder)
vae_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005))

print(f"Dataset Verified. Images: {len(X_train)}")
vae_model.fit(X_train, epochs=EPOCHS, batch_size=BATCH_SIZE, shuffle=True)

print("Finalizing Latent Clustering...")
z_mean, _, _ = encoder.predict(X_train)
kmeans = KMeans(n_clusters=N_CLUSTERS, n_init=20, random_state=42)
y_pred_clusters = kmeans.fit_predict(z_mean)

def generate_unsupervised_masks(encoder, X):
    _, _, z = encoder.predict(X)
    segments = []
    for i in range(len(X)):
        latent_map = np.abs(z[i]).reshape(8, 4)
        mask_res = cv2.resize(latent_map, (IMG_SIZE, IMG_SIZE))
        mask_norm = (mask_res - mask_res.min()) / (mask_res.max() - mask_res.min() + 1e-7)
        segments.append((mask_norm > 0.5).astype(np.uint8))
    return np.array(segments)

unsupervised_masks = generate_unsupervised_masks(encoder, X_train)

encoder.save('advanced_urban_encoder.h5')
decoder.save('advanced_urban_decoder.h5')
np.save('unsupervised_segments.npy', unsupervised_masks)

final_iou = jaccard_score(Y_val.flatten(), unsupervised_masks.flatten(), average='binary')
print(f"Deployment Ready. Unsupervised IoU Score: {final_iou:.4f}")

